name       : languagetool
version    : '5.6'
release    : 1
source     :
    - git|https://github.com/languagetool-org/languagetool.git : v5.6
license    : LGPL-2.1-only
component  : office.viewers
summary    : Style and Grammar Checker for 25+ Languages
description: |
    LanguageTool is an Open Source proofreading software for English, French, German, Polish, Russian, and more than 20 other languages. It finds many errors that a simple spell checker cannot detect.
builddeps  :
    - openjdk-11
    - apache-maven
rundeps    :
    - openjdk-11
networking : yes
environment: |
    JAVA_HOME=/usr/lib64/openjdk-11
    PATH=$JAVA_HOME/bin:$PATH
build      : |
    $workdir/build.sh languagetool-standalone package -DskipTests -Dmaven.repo.local=$workdir/.m2
install    : |
    install -dDm00755 $installdir/usr/share/languagetool/{libs,META-INF,org}
    cp $workdir/languagetool-standalone/target/LanguageTool-5.6/LanguageTool-5.6/*.jar $installdir/usr/share/languagetool/
    cp $workdir/languagetool-standalone/target/LanguageTool-5.6/LanguageTool-5.6/libs/*.jar $installdir/usr/share/languagetool/libs/
    cp -R $workdir/languagetool-standalone/target/LanguageTool-5.6/LanguageTool-5.6/META-INF/* $installdir/usr/share/languagetool/META-INF/
    cp -R $workdir/languagetool-standalone/target/LanguageTool-5.6/LanguageTool-5.6/org/* $installdir/usr/share/languagetool/org/
    install -Dm00755 $pkgfiles/languagetool -t $installdir/usr/bin
check      : |
    #mvn test -Dmaven.repo.local=$workdir/.m2
